// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  describe('myApp.view2 module', function() {
    beforeEach(function() {
      return module('myApp.view2');
    });
    return describe('view2 controller', function() {
      return it('should ....', inject(function($controller) {
        var view2Ctrl;
        view2Ctrl = $controller('View2Ctrl');
        return expect(view2Ctrl).toBeDefined();
      }));
    });
  });

}).call(this);
