// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('myApp', ['ngRoute', 'myApp.view1', 'myApp.view2']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.otherwise({
        redirectTo: '/view1'
      });
    }
  ]);

}).call(this);
