// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  describe('myApp.view1 module', function() {
    beforeEach(function() {
      return module('myApp.view1');
    });
    return describe('view1 controller', function() {
      return it('should ....', inject(function($controller) {
        var view1Ctrl;
        view1Ctrl = $controller('View1Ctrl');
        return expect(view1Ctrl).toBeDefined();
      }));
    });
  });

}).call(this);
